### ISSUE TITLE
Question: Avoid sequence of codons

### ISSUE THREAD

**Issue by kmcgrathgenerate** [Edinburgh-Genome-Foundry/DnaChisel#80] opened 2024-06-13 12:58 UTC
I have several sequences of codons that I want to remove, not necessarily a pattern within the whole sequence. The codon sequences are all 3 long (9 NT). I am having trouble finding a solution. I often find dna sequences that are unable to find solutions exhaustively and it looks like it might be trying to change the sequence in the wrong location. Here is what I currently have:

```
class AvoidTricodons(Specification):
    def __init__(self):
        self.avoid_tricodons = AVOID_TRICODONS

    def evaluate(self, problem):
        sequence = problem.sequence
        locations = []
        for i in range(len(sequence) - 6):
            codon_triplet = (
                sequence[i : i + 3] + sequence[i + 3 : i + 6] + sequence[i + 6 : i + 9]
            )
            if codon_triplet in self.avoid_tricodons:
                locations.append(Location(i, i + 9))

        return SpecEvaluation(
            self,
            problem,
            score=-len(locations),
            locations=locations,
            message=("Sequence codons found at: " + ", ".join(map(str, locations))),
        )
        
        
    ```

Is there something I am doing wrong?

**Comment by kmcgrathgenerate** [comment] 2024-06-13 14:42
I was able to get working solution using a combination of avoid pattern & making sure each location found is on a codon boundary. Just wasn't sure why the above was not working

**Comment by veghp** [comment] 2024-06-21 15:39
I have a couple questions before looking into it in detail; in line `for i in range(len(sequence) - 6):` why do you have 6?
Also should the range not increment by steps of 3?

Is this:
```
sequence[i : i + 3] + sequence[i + 3 : i + 6] + sequence[i + 6 : i + 9]
```
not equivalent to `sequence[i : i + 9]` ?

Could increasing `max_random_iters` help it find a solution?

How many codontriplets do you check for (approximately)? What is in AVOID_TRICODONS?

I'm happy to try the code, if you could please provide a working example? E.g. a bit more code context and perhaps the contents of AVOID_TRICODONS.

**Comment by kmcgrathgenerate** [comment] 2024-06-21 16:52
Hello @veghp, you are correct about both the sequence[i : 1+9] and the increment by 3. I boiled down my original class to this in the hopes to make it simpler but I made a mistake and my looping is incorrect. it should be a range incrementing by 3. 

The reason I write the [ i : i + 9] was just for readability early on, it doesn't need to be the way I wrote it. 

In my previous comment I wrote that I created N constraints for each tricodon I did not want that was basically "avoid pattern" but checking the pattern starts on a codon and this is working well. 

I am going to get back to an old commit and try it again with increasing the max iters. thanks!

**Comment by kmcgrathgenerate** [comment] 2024-06-21 17:04
After making the tweaks, I believe I have been here before where it works on many sequences but I get this error sometimes:

```class AvoidTricodons(Specification):
    def __init__(self):
        self.avoid_tricodons = AVOID_TRICODONS

    def evaluate(self, problem):
        sequence = problem.sequence
        locations = []
        for i in range(0, len(sequence) - 9, 3):
            codon_triplet = sequence[i : i + 9]
            if codon_triplet in self.avoid_tricodons:
                locations.append(Location(i, i + 9))

        return SpecEvaluation(
            self,
            problem,
            score=-len(locations),
            locations=locations,
            message=("Sequence codons found at: " + ", ".join(map(str, locations))),
        )
```

```                if (i < (len(locations) - 1)) and (
                    locations[i + 1].overlap_region(new_location)
                ):
>                   this_local_constraint = constraint.localized(
                        new_location, with_righthand=False, problem=self
                    )
E                   TypeError: Specification.localized() got an unexpected keyword argument 'with_righthand'

/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/dnachisel/DnaOptimizationProblem/mixins/ConstraintsSolverMixin.py:244: TypeError

```

I think i've been close here before but then when I tried to override this function "localized()", i could not get it to work. Have you seen this before?

**Comment by kmcgrathgenerate** [comment] 2024-06-21 17:17
I also overwrote the localized function to just return self. not sure if that is the best way. But when I run on longer sequences, I often get exhaustive searches that cannot find a solution. 3 or 4 out of every random 50 AA sequences I generate

**Comment by veghp** [comment] 2024-07-17 13:47
I've tried your updated code (https://github.com/Edinburgh-Genome-Foundry/DnaChisel/issues/80#issuecomment-2183121437) on a simple example and it worked. I'm happy to try with sequences / tricodons that failed, if you post the full code here. Are we certain that there exist a solution for those cases? By exhaustive searches did you mean the increasing of `max_random_iters`?

**Comment by krixen55** [comment] 2024-07-17 13:55
My latest code that failed:

```
class AvoidTricodons(Specification):
    def __init__(self):
        self.avoid_tricodons = AVOID_TRICODONS

    def evaluate(self, problem):
        sequence = problem.sequence
        locations = []
        for i in range(0, len(sequence) - 9, 3):
            codon_triplet = sequence[i : i + 9]
            if codon_triplet in self.avoid_tricodons:
                locations.append(Location(i, i + 9))

        return SpecEvaluation(
            self,
            problem,
            score=-len(locations),
            locations=locations,
            message=("Sequence codons found at: " + ", ".join(map(str, locations))),
        )

    # overwriting with "with_righthand" argument to avoid error
    def localized(self, location, with_righthand=False, problem=None):
        return self
```

When sequences fail, I typically will generate some 50+ random AA sequences of varying lengths [50, 100, 200, 250] and use dnachisels translate. I ensure that the tricodons I want to avoid exist in every one of my test cases. I still get a lot of failures but sometimes it does remove the tricodons.

**Comment by veghp** [comment] 2024-07-17 14:40
Thanks, yes can you please post how you run the code and specify the constraints, a failing example sequence and the avoid_tricodons contents here, or via email (see main github page for address)? So that I can reproduce the problem.

**Comment by krixen55** [comment] 2024-07-17 17:56
@veghp I went back to re-run this code with random sequences to find you one that fails but for whatever reason, I no longer see any failures. I even went as far as to run 500+ sequences each of 300 long that contain a tricodon i want to avoid and i dont have any issues. I am not entirely sure what changed since last month as I put this branch aside. 

In your opinion, given that my avoiding tricodon list is in the 700+ range, is it better to add this single constraint or 700 smaller constraints? or does it not really matter?

**Comment by kmcgrathgenerate** [comment] 2024-07-17 18:17
Here is an AA sequence that fails to find a solution:

MISNSWYFQVQHFPWDGGRDRPFQFDKRAGDIQWTEELDHGFCHWQQRYFQGLHPWCCHPEHRILNEEVHGLVDISILGDDKKYRKEFLTRRNAFRAYQ*

and here are the tricodons I want to avoid. 

AVOID_TRICODONS: set[str] = {nn + 3 * X + 3 * Y + H for X in "ATGC" for Y in "ATGC" for H in "ATC" for nn in NN}

if I make 700+ constraints for pattern in frame for each of these avoid tricodons, a solution is found. If I use the code above, it cannot find a solution.

The way I am running this example is adding the avoidtricodons as a constraint:

```
problem = DnaOptimizationProblem(
            sequence=dna_seq,
            constraints=AvoidTricodons(),
            objectives=objectives,
            logger=None,
        )
```

**Comment by veghp** [comment] 2024-11-07 19:19
I'm closing this as the initial code example worked for me. Please post a full working example that reproduces the problem and I'll look into it again.

**Closed as completed by veghp** 2024-11-07 19:19 UTC
